# NOTE:
# This system runs in CPU-only mode by default due to VRAM limits.
# GPU/CUDA support can be enabled by modifying the code
# in HybridSTT and WhisperSTT.
model:
  size: "small"
  device: "cpu"
  compute_type: "float32"
  language: null

performance:
  fp16: true
  beam_size: 5
  best_of: 5

whisper:
  model_size: "small"
  language: null
  device: "cuda"
  
indic:
  model_name: "gvs/wav2vec2-large-xlsr-malayalam"
  language_code: "ml"
  device: "cuda"

audio:
  sample_rate: 16000
  channels: 1
  chunk_duration: 5

language_detection:
  enabled: true
  threshold: 0.6
  supported_languages:
    - en
    - ar
    - ml

